config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'

  resources :categories do
    resources :item_categories
  end
  resources :users do
    resources :items, expect: [:index] do
      collection do
        get :my_items
      end
      resources :bookings
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :item_categories
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  has_many :item_categories, dependent: :destroy

  validates :name, :description, :price, presence: true
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :category
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :items
  has_many :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
    @user = current_user.id
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @user = current_user
    @item = Item.find(params[:item_id])
    @booking = Booking.new
  end

  def create
    @item = Item.find(params[:item_id])
    @user = current_user
    @booking = Booking.new(params_booking)
    @booking.user = @user
    @booking.item = @item
    if @booking.save
      redirect_to user_item_bookings_path
    else
      render :new
    end
  end

  def edit
    @user = current_user
    @item = Item.find(params[:item_id])
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(params_booking)
      redirect_to user_item_bookings_path
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_item_bookings_path
  end

  private

  def params_booking
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @items = Item.all
  end
end

app/controllers/item_categories_controller.rb
class ItemCategoriesController < ApplicationController
  def show
    @item_category = ItemCategory.find(params[:id])
    @category = Category.find(params[:category_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @items = Item.first(4)
  end

  def new
    @item = Item.new
    @user = current_user
  end


  def create
    @user = current_user
    @item = Item.new(params_item)
    @item.user = @user
    if @item.save
      redirect_to new_user_item_booking_path(@user, @item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    @user = current_user
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(params_item)
      redirect_to my_items_user_items_path(current_user, @item)
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to my_items_user_items_path(current_user, @item)
  end

  def my_items
      @items = Item.where(user: current_user)
  end

  private

  def params_item
    params.require(:item).permit(:name, :description, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<%# <h1>Edit bookings</h1> %>
<div>
  <h1>
    <%= @item.name %>
  </h1>
</div>

<div>
  <%= simple_form_for [@user, @item, @booking] do |f| %>
    <%= f.input :start_date, label: "First Day :"  %>
    <%= f.input :end_date, label: "Last Day :" %>
    <%= f.submit 'Reserve', class: 'btn-back2list' %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="d-flex justify-content-around" style= "margin-top: 20px">
<div style= "width: 200px ; margin-left: 30px"> <h3>Items</h3></div>
<div style="margin-right: 28px"> <h3>Start Date</h3> </div>
 <div style= "margin-right: 20px"><h3>End Date</h3></div>
</div>
<ul class="list-group list-group-flush">
  <% @bookings.each do |booking|%>
    <div>
      <li class="list-group-item" style= "margin-bottom: 15px ">
        <div class="d-flex justify-content-between" style= "height: 3rem">
          <div class= "text" style = "margin-top: 10px">
            <%= link_to booking.item.name, user_item_path(current_user, booking.item) %>
          </div>
          <div class= "text-date-start " style = "margin-top: 15px ; margin-right: 31px">
            <%= booking.start_date.strftime('%d/%m/%Y')%>
          </div>
          <div class = "text-date-end " style = "margin-top: 15px">
            <%= booking.end_date.strftime('%d/%m/%Y')%>
          </div>
        </div>
        <div style="text-align: right; margin-bottom:-10px">
          <%= link_to 'Edit', edit_user_item_booking_path(current_user, booking.item.id, booking) %>
          <%= link_to 'Delete', user_item_booking_path(current_user ,booking.item, booking), method: :delete %>
        </div>
      </li>
    </div>
  <% end %>
</ul>

app/views/bookings/new.html.erb
<div class="newbooking">
  <div class="containerctv">
    <div class="card-trip">
      <% if @item.photo.attached? %>
        <%= cl_image_tag @item.photo.key, crop: :fill %>
      <% else %>
        <img src="https://avatars.githubusercontent.com/u/55115774?v=4" alt="photo">
      <% end %>
      <div class="card-trip-infos">
        <div>
          <h2><%= @item.name %></h2>
          <p><%= @item.description%></p>
        </div>
        <h2 class="card-trip-pricing">$ <%=@item.price%> /day</h2>
      </div>
    </div>
  </div>

  <div class="formbooking">
    <%= simple_form_for [@user, @item, @booking] do |f| %>
      <%= f.input :start_date, label: "First Day :"  %>
      <%= f.input :end_date, label: "Last Day :" %>
      <%= f.submit 'Reserve', class: 'btn-back2list' %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<h1> <%= @booking.item.name %> </h1>


<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item"> <%= @booking.start_date %> </li>
    <li class="list-group-item"> <%= @booking.end_date %> </li>
    <li class="list-group-item"> <%= @booking.user.first_name %> <%= @booking.user.last_name %></li>
  </ul>
</div>

app/views/categories/show.html.erb
<h2 style=
    "text-align: center;
    margin-top: 30px;
    opacity: 0.7;">
    <%= @category.name %></h2>
<div class="category-container">
  <div class="items-homepage" style="margin-top: 3%" id="linkhometoitem">
    <% @items.each do |item| %>
      <div class="card" style="width: 18rem;">
        <% if item.photo.attached? %>
          <%= cl_image_tag item.photo.key, crop: :fill %>
        <% else %>
          <img class="img-item" src="https://avatars.githubusercontent.com/u/55115774?v=4" alt="photo">
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= item.name %></h5>
            <div class="card-info">
              <p class="card-text"><%= item.description %></p>
              <p class="item-price">$ <%= item.price %>/day</p>
            </div>
            <div class="card-btn1">
              <%= link_to "Reserve", new_user_item_booking_path(current_user.id,item) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


app/views/items/edit.html.erb
<div class="new-form" style="margin-top: 75px; margin-left: 400px">
  <%= form_for([@user, @item]) do |f| %>
    <div><%= f.label :name %>
    </div>
    <div>
    <%= f.text_field :name %>
    </div>

  <div style="margin-top: 14px;">
    <div style="display: flex;">
      <%= f.label :description, class: "margin-right "%>
    </div>
    <div style="margin-left: 12px; width: 10px;"><%= f.text_area :description %>
    </div>
  </div>

  <div style="margin-top:25px;">
    <%= f.file_field :photo, as: :file %>
  </div>

  <div style="margin-top: 25px; margin-right: 25px ">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div style="margin-top: 25px">
    <%= f.submit 'add my item' %>
  </div>
  <% end %>
</div>

app/views/items/index.html.erb
<%# banner, revoir bouton, font du text %>
<div class="banner_img">
  <h1> Anyone want to possess incredible POWER</h1>
  <a href="#linkhometoitem" class="btn1">Become a Legend</a>
</div>

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
    <%= link_to category_path(1) do %>
      <%= image_tag 'https://images.unsplash.com/photo-1497124401559-3e75ec2ed794?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2970&q=80', class: "d-block w-100"%>
    <% end %>
      <div class="carousel-caption d-none d-md-block" >
        <h5 class="category-title">MOVIES</h5>
        <p> </p>
      </div>
    </div>
    <div class="carousel-item">
      <%= link_to category_path(2) do %>
        <%= image_tag ( "https://images.unsplash.com/photo-1613376023733-0a73315d9b06?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2970&q=80"),class: "d-block w-100" %>
      <% end %>
      <div class="carousel-caption d-none d-md-block" style="font-size: 18px" class="category-title">
        <h5 class="category-title">ANIMATE</h5>
        <p> </p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="items-homepage" id="linkhometoitem">
  <% @items.each do |item| %>
    <div class="card" style="width: 18rem;">
      <% if item.photo.attached? %>
        <%= cl_image_tag item.photo.key, crop: :fill, class: "img-item" %>
      <% else %>
        <img class="img-item" src="https://avatars.githubusercontent.com/u/55115774?v=4" alt="photo">
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= item.name %></h5>
          <div class="card-info">
            <p class="card-text"><%= item.description %></p>
            <p class="item-price">$ <%= item.price %>/day</p>
          </div>
          <div class="card-btn1">
            <%= link_to "Reserve", new_user_item_booking_path(current_user.id,item) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/items/items.html.erb
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

app/views/items/my_items.html.erb
<h1>My Items</h1>

<div class="items-homepage" id="linkhometoitem">
  <% @items.each do |item| %>
    <div class="card" style="width: 18rem;">
      <% if item.photo.attached? %>
        <%= cl_image_tag item.photo.key, crop: :fill, class: "img-item" %>
      <% else %>
        <img class="img-item" src="https://avatars.githubusercontent.com/u/55115774?v=4" alt="photo">
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= item.name %></h5>
          <div class="card-info">
            <p class="card-text"><%= item.description %></p>
            <p class="item-price">$ <%= item.price %>/day</p>
          </div>
          <div class="card-btn1">
            <%= link_to "Edit", edit_user_item_path(current_user.id,item) %>
            <%= link_to "Delete", user_item_path(current_user.id,item), method: :delete %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="new-form">
  <%= form_for([@user, @item]) do |f| %>
    <div class="attache-name-rectangle">
      <div class="name" ><%= f.label 'Name :' %>
      </div>
      <div class="rectangle-name"> <%= f.text_field :name %>
      </div>
    </div>
    <div class="attache-description-rectangle">
      <div class="description">
        <%= f.label 'description :'%>
      </div>
      <div class="rectangle-description">
        <%= f.text_area :description %>
      </div>
    </div>
    <div class= " attache-parcourir">
      <%= f.file_field :photo %>
    </div>
    <div class= "attache-price">
      <div class= "price"> <%= f.label 'price :' %>
      </div>
      <div class = "rectangle-price">
      <%= f.number_field :price %>
      </div>
    </div>
    <div class = "add-item">
      <%= f.submit 'add my item' %>
    </div>
  <% end %>
</div>

app/views/items/show.html.erb
<%# <div class="containerz">
  <h1>Le Super Article</h1>

  <div class="card-categor">
    <div class="">
      <h2 class="item_name"><%= @item.name %></h2>
      <%# <p><%= @item.description%></p>
      <%# <img> <%= image_tag "marteau_de_thor.jpg"%>
    <%# </div>
  </div>
</div> %>

<%# <div class="container" id = "div_btn_formulaire">
  <%= link_to f.submit 'Soumettre',class: 'btn1'%>
<%# </div> %>
<div class="container-card">
<div class="row">
  <div class="col-7">

  <div class="card-avatar">
    <img src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_1280.png" />


    <div class="d-flex flex-column", style="height: 120px;">
      <div class="card-avatar-infos">
        <h2><%= @item.user.email %> <%= @item.user.last_name %></h2>
        <p> <strong>Email :</strong><%= @item.user.email %>
        <%# <strong>Age :</strong><%= @item.user.age</p> %>
        <p> <strong>Address: </strong><%= @item.user.address %></p>
      </div>
      <div class="rating-css">
        <%# <div>star</div> %>
        <div class="star-icon">
          <input type="radio" name="rating1" id="rating1">
          <label for="rating1" class="fa fa-star"></label>
          <input type="radio" name="rating1" id="rating2">
          <label for="rating2" class="fa fa-star"></label>
          <input type="radio" name="rating1" id="rating3">
          <label for="rating3" class="fa fa-star"></label>
          <input type="radio" name="rating1" id="rating4">
          <label for="rating4" class="fa fa-star"></label>
          <input type="radio" name="rating1" id="rating5">
          <label for="rating5" class="fa fa-star"></label>
        </div>
      </div>
    </div>
  </div>


    <div class="card-trip">
      <div class="btn">
        <%= link_to "Home", root_path, class: "btn btn-gradient" %>
        <%= link_to "Reserve", new_user_item_booking_path(current_user.id, @item), class: "btn btn-gradient" %>
      </div>
      <% if @item.photo.attached? %>
        <%= cl_image_tag @item.photo.key, crop: :fill %>
      <% else %>
        <img src="https://avatars.githubusercontent.com/u/55115774?v=4" alt="photo">
      <% end %>
      <div class="card-trip-infos">
        <div>
          <h2><%= @item.name %></h2>
          <p><%= @item.description%></p>
        </div>
        <h2 class="card-trip-pricing"><%=@item.price%></h2>
      </div>
    </div>
  </div>
  <div class="col-5">
    <div class="container-category">
      <%# @item.first(4).each = %>





<% @items.each do |item| %>
      <div class="d-flex flex-column", style="height: 150px;">
        <div class="box-card-category">
          <div class="card-item-category">
            <% if item.photo.attached? %>
              <%= cl_image_tag item.photo.key, crop: :fill %>
            <% else %>
              <img class="img-item" src="https://avatars.githubusercontent.com/u/55115774?v=4" alt="photo">
            <% end %>
              <%# <img src=<%= item.photo %>
              <%# <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" /> %>
              <div class="card-item-category-infos">
                <h2><%= item.name %>
                <p><%= item.description %></p>
                <%= link_to "Item", root_path%></h2>
                <p></p>
              </div>
          </div>
        </div>
      </div>
<% end %>

          <%# <div class="card-item-category">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
            <div class="card-item-category-infos">
              <h2>Product name</h2>
              <p>Product description with <strong>relevant info</strong> only.</p>
            </div>
          </div> %>
<%#
          <div class="card-item-category">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
            <div class="card-item-category-infos">
              <h2>Product name</h2>
              <p>Product description with <strong>relevant info</strong> only.</p>
            </div>
          </div>

          <div class="card-item-category">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
            <div class="card-item-category-infos">
              <h2>Product name</h2>
              <p>Product description with <strong>relevant info</strong> only.</p>
            </div>
          </div> %>
      </div>
    </div>
    </div>
  </div>
</div>


</div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zero2hero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div style= "min-height: 100vh;">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
      <%= yield %>
    <footer>
      <%= render 'shared/footer' %>
    </footer>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<a href="#" class="btn1">M'INSCRIRE</a>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> and IU Kit because I don't want to prendre la tête.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "occulte.png" %>
    <% end %>
    <h1 id="home-title">Hero2Zero</h1>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My bookings", user_item_bookings_path(current_user, 0), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "+ New item", new_user_item_path(current_user, @item), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Items", my_items_user_items_path(current_user, @items), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://avatars.githubusercontent.com/u/96440289?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", "#", class: "dropdown-item" %>
              <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

 <%# <%= link_to "MyBookings", user_item_bookings_path(current_user.id, @items)'%' %>